INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Wiliam','Ramirez','wiliam1@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Eduar','Ramirez','wiliam2@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Alison','Ramirez','wiliam3@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Neyker','Ramirez','wiliam4@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Julia','Ramirez','wiliam5@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Nayra','Ramirez','wiliam6@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Miria,','Ramirez 4','wiliam7@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Walas','Ramirez 33','wiliam8@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Erick','Ramirez 3','wiliam9@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Josep','Ramirez 12','wiliam@gmail.com','2020-01-01');
