INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Wiliam','Ramirez','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Eduar','Ramirez','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Alison','Ramirez','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Neyker','Ramirez','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Julia','Ramirez','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Nayra','Ramirez','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Miria,','Ramirez 4','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Walas','Ramirez 33','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Erick','Ramirez 3','wiliam@gmail.com','2020-01-01');
INSERT INTO clients (names, lastnames, email, create_at) VALUES ('Josep','Ramirez 12','wiliam@gmail.com','2020-01-01');
